import tweepy
import json

# Generated by creating a Twitter APP here: https://developer.twitter.com/en/apps
with open('config.json') as json_file:
    config = json.load(json_file)

CONSUMER_API_KEY    = config["twitter_api"]["cons_api_key"]
CONSUMER_API_SECRET = config["twitter_api"]["cons_api_sec"]
ACCESS_TOKEN        = config["twitter_api"]["access_token"]
ACCESS_TOKEN_SECRET = config["twitter_api"]["access_secret"]

# Twitter currently allows only 100 Tweets per request:
# https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/get-statuses-lookup
TWEETS_PER_REQUEST = 100


def read_tweet_ids(filepath, batchsize=100):
    """to do"""
    return []


def get_tweet_status(array_of_tweet_ids):
    """to do"""
    return []


def write_tweet_status(filepath):
    """to do"""
    return


def main():
    """Handle the bulk of the execution"""
    return


if __name__ == '__main__':
    main()
