import tweepy
import json
#import pandas as pd

# Generated by creating a Twitter APP here: https://developer.twitter.com/en/apps
with open('data/config.json') as json_file:
    config = json.load(json_file)

CONSUMER_API_KEY    = config["twitter_api"]["cons_api_key"]
CONSUMER_API_SECRET = config["twitter_api"]["cons_api_sec"]
ACCESS_TOKEN        = config["twitter_api"]["access_token"]
ACCESS_TOKEN_SECRET = config["twitter_api"]["access_secret"]

# Twitter currently allows only 100 Tweets per request:
# https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/get-statuses-lookup
TWEETS_PER_REQUEST = 100


def read_tweet_ids(filepath):
    """Read the contents of a file provided as a parameter and return an array of line contents."""
    with open(filepath) as twitter_id_data:
        lines = twitter_id_data.readlines()
    return lines


def get_tweet_statuses(array_of_tweet_ids, batchsize):
    """to do"""
    return []


def write_tweet_status(filepath, array_of_tweet_statuses):
    """Given an array and filepath/ destination, create the file and write the array lines to the file."""
    with open(filepath, 'w') as twitter_status_data:
        for line in array_of_tweet_statuses:
            twitter_status_data.write(line)


def main():
    """Handle the bulk of the execution"""
    sub_tweet_ids_only = []
    all_tweet_statuses = []

    all_tweet_ids = read_tweet_ids('data/public/waseem_labeled_id_data.csv')

    while all_tweet_ids:
        sub_tweet_ids = all_tweet_ids[:TWEET_BATCH_SIZE - 1]
        all_tweet_ids = all_tweet_ids[TWEET_BATCH_SIZE - 1:]
        for line in sub_tweet_ids:
            id_only = line.split(',')[0]
            sub_tweet_ids_only.append(id_only)

        # now need to concat the status onto the original id+val line
        sub_tweet_statuses = tweet_status(api, sub_tweet_ids_only)
        for i in range(0, len(sub_tweet_statuses)):
            old_line = sub_tweet_ids[i].split(',')
            new_line = old_line[0] + ',' + sub_tweet_statuses[i] + ',' + old_line[1]
            all_tweet_statuses.append(new_line)

    write_tweet_status('data/private/waseem_labeled_status_data.csv', all_tweet_statuses)


if __name__ == '__main__':
    #test_pd_file = pd.read_csv('data/private/davidson_labeled_status_data.csv', nrows=15)
    #print(test_pd_file)
    main()
